
      data cost3min/-1d0/,cost3max/1d0/,ndiv_cost3/50/,m_cost3/0/
      data cost4min/-1d0/,cost4max/1d0/,ndiv_cost4/50/,m_cost4/0/
      data cost3colmin/-1d0/,cost3colmax/1d0/,ndiv_cost3col/50/
     &     m_cost3col/0/
      data cost4colmin/-1d0/,cost4colmax/1d0/,ndiv_cost4col/50/
     &     m_cost4col/0/
      data Y3min/-4d0/,Y3max/4d0/,ndiv_Y3/50/,m_Y3/0/
      data Y4min/-4d0/,Y4max/4d0/,ndiv_Y4/50/,m_Y4/0/
      data Y3colmin/-4d0/,Y3colmax/4d0/,ndiv_Y3col/100/,m_Y3col/0/
      data Y4colmin/-4d0/,Y4colmax/4d0/,ndiv_Y4col/100/,m_Y4col/0/
      data eta3min/-5d0/,eta3max/5d0/,ndiv_eta3/100/,m_eta3/0/
      data eta4min/-5d0/,eta4max/5d0/,ndiv_eta4/100/,m_eta4/0/
      data eta3colmin/-5d0/,eta3colmax/5d0/,ndiv_eta3col/50/,
     &     m_eta3col/0/
      data eta4colmin/-5d0/,eta4colmax/5d0/,ndiv_eta4col/50/,
     &     m_eta4col/0/
      data Yffmin/-4d0/,Yffmax/4d0/,ndiv_Yff/100/,m_Yff/0/
      data Pzffmin/0d0/,Pzffmax/-999d0/,ndiv_Pzff/100/,m_Pzff/0/
      data rmassmin/-999d0/,rmassmax/-999d0/,ndiv_rmass/200/,m_rmass/0/
      data betamin/1d-3/,betamax/1d3/,ndiv_beta/200/,m_beta/0/
      data delYmin/0d0/,delYmax/10d0/,ndiv_delY/100/,m_delY/0/
      data Etmin/0d0/,Etmax/-999d0/,ndiv_Et/175/,m_Et/0/
      data pTmin/0d0/,pTmax/-999d0/,ndiv_pT/100/,m_pT/0/
      data yc/0.5d0/, yffcut/0.5d0/, pzffcut/700d0/
      data yffs(1)/0d0/,yffs(2)/0.2d0/,yffs(3)/0.4d0/,yffs(4)/0.6d0/
      data yffs(5)/0.8d0/,yffs(6)/1.0d0/,yffs(7)/1.2d0/,yffs(8)/1.4d0/
      data nasy/18/ ! number of asymmetry distributions defined
